contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #awsomicstest channel"
    url: https://nfcore.slack.com/channels/awsomicstest
    about: Discussion about the nf-core/awsomicstest pipeline
